#!/bin/bash

name=$(basename $0)

os=$(uname -a)

echo -e "$name: Operating System is $os"

echo -e "Major lab 1,L01: bash script named $name"

if [ $# = 1 ]; then
  #arguments =1
  if [ -d $1 ];then
  #$1 is present
    x=`ls $1`
    if [ -z $x ];then
      #Directory exists and is empty
      echo -e "$name: $1 exists and is empty"

    else
      #Directory exists and is not empty
      echo -e "$name: $1 directory exists, is non-empty emptying it"
      echo -e "$name: contents of directory $1"
      ls $1
      echo -e "$name: removing regular files from $1"

      x=`ls $1`
      cd $1 #changes to new directory
        for i in $x
        #deleting files one by one
        do 
          if [ -f $i ]; then
            #checks if content is a file
            echo -e "$name: removing regular file $i from $1"
            rm $i 


          fi
          done
      fi
  else
  #$1 not present

    echo -e "$name: $1 directory does not exist, creating it"
    mkdir $1

  
  fi


echo -e "$name: putting 3 required files in $1"
cd $1
for i in {1..3}
do
echo "Please give me a 100% on this lab" > required.file$i
done

else 
#arguments dont equal 1
echo -e "$name: wrong number of command line arguments"
echo -e "usage -- $name $(dirname $0)"

fi
